# Generated by Django 5.1.6 on 2025-02-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
