# Generated by Django 5.1.6 on 2025-02-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_image_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
